name: Build & Deploy Module

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare files for GitHub Pages
        run: |
          mkdir public
          # ✅ 1. Архив модуля
          cd module
          zip -r ../public/draw-sphere.zip .
          cp module.json ../public/module.json
          cd ..

          # ✅ 2. Серверная часть — публикуем просто как JS-файл
          mkdir -p public/server
          cp server/main.js public/server/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages